
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
