// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://habpxrkueuqmumbdnuan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhYnB4cmt1ZXVxbXVtYmRudWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjQ1NDIsImV4cCI6MjA1ODY0MDU0Mn0.camWZ6D3xDm4fnfBSyAWBoSLYK2U57HMfix8s8fimWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);